name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore Game.sln
      - name: Build
        run: dotnet build Game.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test Game.sln --configuration Release --no-build --collect "XPlat Code Coverage"
